// AUTO-GENERATED by status-contract/sync.mjs — DO NOT EDIT.
// Source of truth: /status-contract/contract.json in the agentgram main repo.
// To change a phase, icon, label key, or timing, edit that file and run
// `node status-contract/sync.mjs`.

import { Activity, Brain, Clock, Pen, Search, Users, Wrench, type LucideIcon } from "lucide-react";

// --- Streaming (per-conversation `message_streaming` events) ---

export const STREAM_STATUSES = ["started","streaming","complete","cancelled"] as const;
export type StreamStatus = (typeof STREAM_STATUSES)[number];

export const STREAM_PHASES = ["thinking","tool_call","writing","analyzing","queued","waiting"] as const;
export type StreamPhase = (typeof STREAM_PHASES)[number];

// --- Global per-agent activity (`agent_activity_changed` events) ---
// Same vocabulary as StreamPhase plus "working" (has an active task but not
// streaming) and minus "queued" (an online/offline signal, not an activity).

export const AGENT_ACTIVITIES = ["thinking","tool_call","writing","analyzing","waiting","working"] as const;
export type AgentActivity = (typeof AGENT_ACTIVITIES)[number];

// --- Presence / runtime ---

export const PRESENCES = ["online_local","offline"] as const;
export type AgentPresence = (typeof PRESENCES)[number];

export const RUNTIMES = ["local","org_host"] as const;
export type AgentRuntime = (typeof RUNTIMES)[number];

export const PRESENCE_MODES = ["always_on","wake_on_demand","manual"] as const;
export type PresenceMode = (typeof PRESENCE_MODES)[number];

// --- Icon / label / animation maps (shared by StreamingBubble + activity indicators) ---

export type PhaseOrActivity = StreamPhase | AgentActivity;

export const PHASE_ICONS: Record<PhaseOrActivity, LucideIcon> = {
  "thinking": Brain,
  "tool_call": Wrench,
  "writing": Pen,
  "analyzing": Search,
  "queued": Clock,
  "waiting": Users,
  "working": Activity,
};

// i18n KEYS (fully namespace-qualified), not resolved strings — resolve with
// t() at render so language switches live.
export const STREAM_PHASE_LABEL_KEYS: Record<StreamPhase, string> = {
  "thinking": "chat:streamPhase.thinking",
  "tool_call": "chat:streamPhase.toolCall",
  "writing": "chat:streamPhase.writing",
  "analyzing": "chat:streamPhase.analyzing",
  "queued": "chat:streamPhase.queued",
  "waiting": "chat:streamPhase.waiting",
};

export const ACTIVITY_LABEL_KEYS: Record<AgentActivity, string> = {
  "thinking": "chat:activity.thinking",
  "tool_call": "chat:activity.toolCall",
  "writing": "chat:activity.writing",
  "analyzing": "chat:activity.analyzing",
  "waiting": "chat:activity.waiting",
  "working": "chat:activity.working",
};

export const STREAM_PHASE_FALLBACK_LABEL_KEY = "chat:streamPhase.working";
export const ACTIVITY_FALLBACK_LABEL_KEY = "chat:activity.working";

// True when the phase/activity represents the agent actively producing
// output (vs. passively queued/waiting). Drives pulse/animation.
export const PHASE_IS_ACTIVE: Record<PhaseOrActivity, boolean> = {
  "thinking": true,
  "tool_call": true,
  "writing": true,
  "analyzing": true,
  "queued": false,
  "waiting": false,
  "working": true,
};

// --- Timing constants ---

// Client-side decay for typing indicators (no explicit stop event).
export const TYPING_TIMEOUT_HUMAN_MS = 3000;
export const TYPING_TIMEOUT_AGENT_MS = 30000;

// A stream with no update for this long is orphaned (bridge died and the
// backend TimeoutServer's cancel was missed). Must stay above the backend's
// worst-case forced-cancel latency.
export const STALE_STREAM_MS = 75000;

// How long a completed stream bubble lingers before clearing.
export const STREAM_COMPLETE_LINGER_MS = 3000;

// Reaper sweep cadence for the above.
export const STREAM_SWEEP_INTERVAL_MS = 10000;
