// AUTO-GENERATED by i18n/sync.mjs — DO NOT EDIT.
// Source of truth: /i18n/locales in the agentgram main repo.
// To change copy or add a language, edit those JSON files and run `node i18n/sync.mjs`.

export const SUPPORTED_LOCALES = ["en","es"] as const;

export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

export const DEFAULT_LOCALE: SupportedLocale = "en";

// Endonyms — each language named in itself; never translated.
export const LOCALE_LABELS: Record<SupportedLocale, string> = {
  "en": "English",
  "es": "Español"
};

export const NAMESPACES = ["auth","chat","common","nav","settings"] as const;

export type Namespace = (typeof NAMESPACES)[number];

export const resources = {
  "en": {
    "auth": {
      "acceptInvitation": "Accept your invitation",
      "alreadyHaveAccount": "Already have an account?",
      "backToSignIn": "Back to sign in",
      "checkYourEmail": "Check your email",
      "confirmEmailMessage": "Check your email to confirm your account.",
      "confirmPassword": "Confirm Password",
      "confirmationSent": "We sent a confirmation link to your email. Please confirm your account, then sign in.",
      "createAccount": "Create Account",
      "displayName": "Display Name",
      "dontHaveAccount": "Don't have an account?",
      "email": "Email",
      "enterEmailAndPassword": "Please enter email and password",
      "errors": {
        "displayNameTooLong": "Display name must be {{max}} characters or fewer.",
        "emailPasswordRequired": "Email and password are required.",
        "handleTaken": "That handle is already taken.",
        "invitePreviewFailed": "Could not load invitation",
        "loginFailed": "Login failed.",
        "passwordTooShort": "Password must be at least 6 characters.",
        "passwordsDontMatch": "Passwords do not match.",
        "signupFailed": "Signup failed."
      },
      "forgotPassword": "Forgot password?",
      "goToSignIn": "Go to Sign In",
      "handle": "Handle",
      "handleAvailable": "Handle is available.",
      "handleChecking": "Checking…",
      "handleFormatHint": "1–15 characters: lowercase letters, numbers, or underscores.",
      "inviteEmailLocked": "This invitation was sent to {{email}}. To use a different address, ask your admin to send a new invitation.",
      "inviteSignInDescription": "Once you sign in, you'll be added to the team.",
      "inviteSignupDescription": "Create your Simplifi account to join the team.",
      "inviteSignupOrgDescription": "Create your Simplifi account to join {{orgName}} as {{role}}.",
      "joinOrg": "Join {{orgName}}",
      "password": "Password",
      "placeholders": {
        "email": "you@example.com",
        "handle": "yourhandle",
        "passwordMin": "Min. 6 characters",
        "yourName": "Your name"
      },
      "signIn": "Sign In",
      "signInSubtitle": "Sign in to Simplifi",
      "signInToAcceptInvite": "Sign in to accept your invitation",
      "signUp": "Sign Up",
      "signUpSubtitle": "Create your account",
      "signingIn": "Signing in...",
      "signupSubtitle": "Get started with Simplifi",
      "tagline": "Agent Management System",
      "welcomeBack": "Welcome back"
    },
    "chat": {
      "composerPlaceholder": "Type a message...",
      "composerPlaceholderFile": "Add context for this file...",
      "composerPlaceholderImage": "Describe this image...",
      "jumpToLatest": "Jump to latest",
      "members_one": "{{count}} member",
      "members_other": "{{count}} members",
      "newChat": "New Chat",
      "newMessages": "New messages",
      "noConversations": "No conversations yet",
      "typing_one": "{{name}} is typing...",
      "typing_other": "{{count}} people are typing..."
    },
    "common": {
      "add": "Add",
      "back": "Back",
      "cancel": "Cancel",
      "change": "Change",
      "close": "Close",
      "confirm": "Confirm",
      "connected": "Connected",
      "copied": "Copied",
      "copy": "Copy",
      "create": "Create",
      "delete": "Delete",
      "disabled": "Disabled",
      "disconnected": "Disconnected",
      "dismiss": "Dismiss",
      "done": "Done",
      "download": "Download",
      "edit": "Edit",
      "enabled": "Enabled",
      "error": "Something went wrong",
      "loading": "Loading...",
      "next": "Next",
      "no": "No",
      "none": "None",
      "off": "Off",
      "offline": "Offline",
      "on": "On",
      "online": "Online",
      "open": "Open",
      "optional": "Optional",
      "refresh": "Refresh",
      "remove": "Remove",
      "rename": "Rename",
      "required": "Required",
      "retry": "Retry",
      "save": "Save",
      "saved": "Saved",
      "saving": "Saving...",
      "search": "Search",
      "send": "Send",
      "share": "Share",
      "today": "Today",
      "unknown": "Unknown",
      "update": "Update",
      "upload": "Upload",
      "view": "View",
      "yes": "Yes",
      "yesterday": "Yesterday",
      "you": "You"
    },
    "nav": {
      "agents": "Agents",
      "agentsOnline": "Agents ({{online}}/{{total}} online)",
      "agentsOnlineTitle": "{{online}}/{{total}} online",
      "canvas": "Canvas",
      "chats": "Chats",
      "files": "Files",
      "friends": "Friends",
      "location": "Location",
      "members": "Members",
      "platform": "Platform",
      "profile": "Profile",
      "settings": "Settings",
      "signOut": "Sign Out",
      "tasks": "Tasks",
      "templates": "Templates"
    },
    "settings": {
      "advanced": {
        "flowDebug": "Flow Control Debug",
        "flowDebugDescription": "Show real-time flow control events (backoff, suppression) in chat",
        "startFresh": "Start Fresh / Replay Onboarding",
        "startFreshDescription": "Wipe all agents, memories, routines & settings, then start onboarding over",
        "testReminder": "Test Reminder",
        "testReminderDescription": "Fire a sample reminder in ~5 seconds to check the toast + push"
      },
      "connections": {
        "subtitle": "Link external services to enable agent integrations."
      },
      "customApis": {
        "add": "Add Custom API",
        "subtitle": "Connect custom service endpoints for agent use. Stored locally on this device."
      },
      "designDebug": {
        "hint": "Also toggles with ⌘⇧D",
        "label": "Design-system debug"
      },
      "language": {
        "description": "Language used across the app interface",
        "label": "Language",
        "system": "System default"
      },
      "llmKeys": {
        "subtitle": "Manage multiple keys per provider. The default key is used by all agents unless overridden in agent config."
      },
      "location": {
        "grantedSummary": "{{granted}} of {{total}} granted",
        "perAgentAccess": "Per-Agent Access",
        "perAgentAccessDescription": "Choose which agents can see your location",
        "shareWithAgents": "Share with agents",
        "shareWithAgentsDescription": "Your agents can access your location for local search, weather, and navigation"
      },
      "manage": {
        "connectedAccounts": "Connected Accounts",
        "connectedAccountsDescription": "Link external services for your agents to use",
        "friendsDescription": "Search people, respond to requests, and manage friends",
        "llmKeysDescription": "Anthropic, OpenAI, etc. — used by your agents",
        "templates": "Response Templates",
        "templatesDescription": "Create and manage templates for agent result presentation"
      },
      "notificationPrefs": {
        "agentActivity": "Agent activity",
        "description": "Choose what you get notified about",
        "descriptions": {
          "agentActivity": "Agent status changes, errors, escalations",
          "invites": "Agent invite claims and connection requests",
          "mentions": "When you're @mentioned in conversations",
          "messages": "New messages in conversations",
          "pulse": "Proactive alerts from agent pulse checks",
          "reminders": "Date reminders your agents set (birthdays, events)",
          "taskAssigned": "Tasks assigned to you or your agents",
          "taskCompleted": "When tasks you created are finished",
          "taskReminders": "Reminders for stale or overdue tasks"
        },
        "enabledSummary": "{{enabled}} of {{total}} on",
        "invites": "Invites",
        "mentions": "Mentions",
        "messages": "Messages",
        "pulse": "Pulse",
        "reminders": "Reminders",
        "taskAssigned": "Task assigned",
        "taskCompleted": "Task completed",
        "taskReminders": "Task reminders"
      },
      "profile": {
        "avatarUploadFailed": "Failed to upload avatar",
        "firstName": "First Name",
        "lastName": "Last Name",
        "tapToChangePhoto": "Tap to change photo",
        "updated": "Profile updated successfully"
      },
      "sections": {
        "advanced": "Advanced",
        "appearance": "Appearance",
        "cloudExecution": "Cloud Execution",
        "cloudHosts": "Cloud Hosts",
        "connections": "Connections",
        "customApis": "Custom APIs",
        "friends": "Friends",
        "language": "Language",
        "llmKeys": "LLM Keys",
        "locationSharing": "Location Sharing",
        "manage": "Manage",
        "memory": "Memory",
        "notifications": "Notifications",
        "profile": "Profile",
        "region": "Region"
      },
      "signOutConfirm": "Are you sure you want to sign out?",
      "theme": {
        "alwaysDark": "Always dark",
        "alwaysLight": "Always light",
        "currentlyShowing": "Currently showing {{theme}}",
        "dark": "Dark",
        "description": "Choose how the app looks",
        "fromSystem": "(from system)",
        "label": "Theme",
        "light": "Light",
        "matchSystem": "Match OS setting",
        "railTooltip": "Theme: {{preference}} (now {{resolved}})",
        "system": "System"
      },
      "timezone": {
        "current": "Current timezone",
        "description": "Used for scheduling and reminders",
        "detail": "Drives how agents interpret “today” and “tomorrow”, and the local time used by routine schedules. Auto-detected from your device on login — change it here if it's wrong or you're traveling.",
        "label": "Timezone",
        "noMatches": "No timezones match \"{{query}}\"",
        "searchPlaceholder": "Search timezones (e.g. New York, Tokyo)",
        "tapToChange": "{{timezone}} — tap to change",
        "useBrowser": "Use browser timezone",
        "useDevice": "Use device timezone"
      },
      "title": "Profile & Settings"
    }
  },
  "es": {
    "auth": {
      "acceptInvitation": "Acepta tu invitación",
      "alreadyHaveAccount": "¿Ya tienes una cuenta?",
      "backToSignIn": "Volver a iniciar sesión",
      "checkYourEmail": "Revisa tu correo",
      "confirmEmailMessage": "Revisa tu correo para confirmar tu cuenta.",
      "confirmPassword": "Confirmar contraseña",
      "confirmationSent": "Te enviamos un enlace de confirmación a tu correo. Confirma tu cuenta y luego inicia sesión.",
      "createAccount": "Crear cuenta",
      "displayName": "Nombre para mostrar",
      "dontHaveAccount": "¿No tienes una cuenta?",
      "email": "Correo electrónico",
      "enterEmailAndPassword": "Introduce tu correo electrónico y contraseña",
      "errors": {
        "displayNameTooLong": "El nombre para mostrar debe tener {{max}} caracteres o menos.",
        "emailPasswordRequired": "El correo y la contraseña son obligatorios.",
        "handleTaken": "Ese handle ya está en uso.",
        "invitePreviewFailed": "No se pudo cargar la invitación",
        "loginFailed": "Error al iniciar sesión.",
        "passwordTooShort": "La contraseña debe tener al menos 6 caracteres.",
        "passwordsDontMatch": "Las contraseñas no coinciden.",
        "signupFailed": "Error al registrarse."
      },
      "forgotPassword": "¿Olvidaste tu contraseña?",
      "goToSignIn": "Ir a iniciar sesión",
      "handle": "Handle",
      "handleAvailable": "El handle está disponible.",
      "handleChecking": "Comprobando…",
      "handleFormatHint": "De 1 a 15 caracteres: letras minúsculas, números o guiones bajos.",
      "inviteEmailLocked": "Esta invitación se envió a {{email}}. Para usar otra dirección, pide a tu administrador que envíe una nueva invitación.",
      "inviteSignInDescription": "En cuanto inicies sesión, se te añadirá al equipo.",
      "inviteSignupDescription": "Crea tu cuenta de Simplifi para unirte al equipo.",
      "inviteSignupOrgDescription": "Crea tu cuenta de Simplifi para unirte a {{orgName}} como {{role}}.",
      "joinOrg": "Únete a {{orgName}}",
      "password": "Contraseña",
      "placeholders": {
        "email": "tu@ejemplo.com",
        "handle": "tuhandle",
        "passwordMin": "Mín. 6 caracteres",
        "yourName": "Tu nombre"
      },
      "signIn": "Iniciar sesión",
      "signInSubtitle": "Inicia sesión en Simplifi",
      "signInToAcceptInvite": "Inicia sesión para aceptar tu invitación",
      "signUp": "Registrarse",
      "signUpSubtitle": "Crea tu cuenta",
      "signingIn": "Iniciando sesión...",
      "signupSubtitle": "Empieza con Simplifi",
      "tagline": "Sistema de gestión de agentes",
      "welcomeBack": "Bienvenido de nuevo"
    },
    "chat": {
      "composerPlaceholder": "Escribe un mensaje...",
      "composerPlaceholderFile": "Añade contexto para este archivo...",
      "composerPlaceholderImage": "Describe esta imagen...",
      "jumpToLatest": "Ir a lo último",
      "members_one": "{{count}} miembro",
      "members_other": "{{count}} miembros",
      "newChat": "Nuevo chat",
      "newMessages": "Mensajes nuevos",
      "noConversations": "Aún no hay conversaciones",
      "typing_one": "{{name}} está escribiendo...",
      "typing_other": "{{count}} personas están escribiendo..."
    },
    "common": {
      "add": "Añadir",
      "back": "Atrás",
      "cancel": "Cancelar",
      "change": "Cambiar",
      "close": "Cerrar",
      "confirm": "Confirmar",
      "connected": "Conectado",
      "copied": "Copiado",
      "copy": "Copiar",
      "create": "Crear",
      "delete": "Eliminar",
      "disabled": "Deshabilitado",
      "disconnected": "Desconectado",
      "dismiss": "Descartar",
      "done": "Listo",
      "download": "Descargar",
      "edit": "Editar",
      "enabled": "Habilitado",
      "error": "Algo salió mal",
      "loading": "Cargando...",
      "next": "Siguiente",
      "no": "No",
      "none": "Ninguno",
      "off": "Desactivado",
      "offline": "Desconectado",
      "on": "Activado",
      "online": "En línea",
      "open": "Abrir",
      "optional": "Opcional",
      "refresh": "Actualizar",
      "remove": "Quitar",
      "rename": "Renombrar",
      "required": "Obligatorio",
      "retry": "Reintentar",
      "save": "Guardar",
      "saved": "Guardado",
      "saving": "Guardando...",
      "search": "Buscar",
      "send": "Enviar",
      "share": "Compartir",
      "today": "Hoy",
      "unknown": "Desconocido",
      "update": "Actualizar",
      "upload": "Subir",
      "view": "Ver",
      "yes": "Sí",
      "yesterday": "Ayer",
      "you": "Tú"
    },
    "nav": {
      "agents": "Agentes",
      "agentsOnline": "Agentes ({{online}}/{{total}} en línea)",
      "agentsOnlineTitle": "{{online}}/{{total}} en línea",
      "canvas": "Lienzo",
      "chats": "Chats",
      "files": "Archivos",
      "friends": "Amigos",
      "location": "Ubicación",
      "members": "Miembros",
      "platform": "Plataforma",
      "profile": "Perfil",
      "settings": "Ajustes",
      "signOut": "Cerrar sesión",
      "tasks": "Tareas",
      "templates": "Plantillas"
    },
    "settings": {
      "advanced": {
        "flowDebug": "Depuración de control de flujo",
        "flowDebugDescription": "Muestra eventos de control de flujo en tiempo real (espera, supresión) en el chat",
        "startFresh": "Empezar de cero / Repetir la configuración inicial",
        "startFreshDescription": "Borra todos los agentes, memorias, rutinas y ajustes, y vuelve a empezar la configuración inicial",
        "testReminder": "Probar recordatorio",
        "testReminderDescription": "Lanza un recordatorio de prueba en ~5 segundos para comprobar el aviso y la notificación push"
      },
      "connections": {
        "subtitle": "Vincula servicios externos para habilitar integraciones de agentes."
      },
      "customApis": {
        "add": "Añadir API personalizada",
        "subtitle": "Conecta endpoints de servicios personalizados para uso de los agentes. Se guardan localmente en este dispositivo."
      },
      "designDebug": {
        "hint": "También se alterna con ⌘⇧D",
        "label": "Depuración del sistema de diseño"
      },
      "language": {
        "description": "Idioma de la interfaz de la aplicación",
        "label": "Idioma",
        "system": "Predeterminado del sistema"
      },
      "llmKeys": {
        "subtitle": "Gestiona varias claves por proveedor. Todos los agentes usan la clave predeterminada salvo que se anule en la configuración del agente."
      },
      "location": {
        "grantedSummary": "{{granted}} de {{total}} con acceso",
        "perAgentAccess": "Acceso por agente",
        "perAgentAccessDescription": "Elige qué agentes pueden ver tu ubicación",
        "shareWithAgents": "Compartir con agentes",
        "shareWithAgentsDescription": "Tus agentes pueden acceder a tu ubicación para búsquedas locales, el tiempo y la navegación"
      },
      "manage": {
        "connectedAccounts": "Cuentas conectadas",
        "connectedAccountsDescription": "Vincula servicios externos para que los usen tus agentes",
        "friendsDescription": "Busca personas, responde a solicitudes y gestiona tus amigos",
        "llmKeysDescription": "Anthropic, OpenAI, etc. — las usan tus agentes",
        "templates": "Plantillas de respuesta",
        "templatesDescription": "Crea y gestiona plantillas para la presentación de resultados de los agentes"
      },
      "notificationPrefs": {
        "agentActivity": "Actividad de agentes",
        "description": "Elige sobre qué quieres recibir notificaciones",
        "descriptions": {
          "agentActivity": "Cambios de estado de los agentes, errores y escalaciones",
          "invites": "Reclamos de invitaciones de agentes y solicitudes de conexión",
          "mentions": "Cuando te mencionan con @ en conversaciones",
          "messages": "Mensajes nuevos en las conversaciones",
          "pulse": "Alertas proactivas de los chequeos de pulso de tus agentes",
          "reminders": "Recordatorios de fechas creados por tus agentes (cumpleaños, eventos)",
          "taskAssigned": "Tareas asignadas a ti o a tus agentes",
          "taskCompleted": "Cuando terminan las tareas que creaste",
          "taskReminders": "Recordatorios de tareas estancadas o vencidas"
        },
        "enabledSummary": "{{enabled}} de {{total}} activadas",
        "invites": "Invitaciones",
        "mentions": "Menciones",
        "messages": "Mensajes",
        "pulse": "Pulso",
        "reminders": "Recordatorios",
        "taskAssigned": "Tarea asignada",
        "taskCompleted": "Tarea completada",
        "taskReminders": "Recordatorios de tareas"
      },
      "profile": {
        "avatarUploadFailed": "No se pudo subir el avatar",
        "firstName": "Nombre",
        "lastName": "Apellidos",
        "tapToChangePhoto": "Toca para cambiar la foto",
        "updated": "Perfil actualizado correctamente"
      },
      "sections": {
        "advanced": "Avanzado",
        "appearance": "Apariencia",
        "cloudExecution": "Ejecución en la nube",
        "cloudHosts": "Hosts en la nube",
        "connections": "Conexiones",
        "customApis": "APIs personalizadas",
        "friends": "Amigos",
        "language": "Idioma",
        "llmKeys": "Claves LLM",
        "locationSharing": "Compartir ubicación",
        "manage": "Gestionar",
        "memory": "Memoria",
        "notifications": "Notificaciones",
        "profile": "Perfil",
        "region": "Región"
      },
      "signOutConfirm": "¿Seguro que quieres cerrar sesión?",
      "theme": {
        "alwaysDark": "Siempre oscuro",
        "alwaysLight": "Siempre claro",
        "currentlyShowing": "Mostrando {{theme}}",
        "dark": "Oscuro",
        "description": "Elige el aspecto de la aplicación",
        "fromSystem": "(del sistema)",
        "label": "Tema",
        "light": "Claro",
        "matchSystem": "Según el sistema",
        "railTooltip": "Tema: {{preference}} (ahora {{resolved}})",
        "system": "Sistema"
      },
      "timezone": {
        "current": "Zona horaria actual",
        "description": "Se usa para programación y recordatorios",
        "detail": "Determina cómo los agentes interpretan «hoy» y «mañana», y la hora local que usan las rutinas programadas. Se detecta automáticamente desde tu dispositivo al iniciar sesión; cámbiala aquí si es incorrecta o si estás de viaje.",
        "label": "Zona horaria",
        "noMatches": "Ninguna zona horaria coincide con \"{{query}}\"",
        "searchPlaceholder": "Buscar zonas horarias (p. ej. Nueva York, Tokio)",
        "tapToChange": "{{timezone}} — toca para cambiar",
        "useBrowser": "Usar la zona horaria del navegador",
        "useDevice": "Usar la zona horaria del dispositivo"
      },
      "title": "Perfil y ajustes"
    }
  }
} as const;
